// <auto-generated />
using System;
using FruitShop.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FruitShop.Api.Migrations
{
    [DbContext(typeof(FruitShopDbContext))]
    [Migration("20260918050737_AddOrderItemPriceChangeReason")]
    partial class AddOrderItemPriceChangeReason
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("FruitShop.Api.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomerTier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("RETAIL");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FruitShop.Api.Models.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PriceChangeReason")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Base price applied");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalLineAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPriceApplied")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("VariantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("VariantId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("FruitShop.Api.Models.PriceRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Active");

                    b.HasKey("Id");

                    b.HasIndex("ParentRuleId");

                    b.ToTable("PriceRules", t =>
                        {
                            t.HasCheckConstraint("CK_PriceRules_Status", "Status IN ('Active', 'Inactive')");
                        });
                });

            modelBuilder.Entity("FruitShop.Api.Models.PriceRuleAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("CalculationBase")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("RunningTotal");

                    b.Property<long>("RuleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.ToTable("PriceRuleActions", t =>
                        {
                            t.HasCheckConstraint("CK_PriceRuleActions_ActionType", "ActionType IN ('OverridePrice', 'PercentageDiscount', 'AmountOff')");

                            t.HasCheckConstraint("CK_PriceRuleActions_CalculationBase", "CalculationBase IN ('OriginalBase', 'RunningTotal')");
                        });
                });

            modelBuilder.Entity("FruitShop.Api.Models.PriceRuleCondition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attribute")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<long>("RuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.ToTable("PriceRuleConditions");
                });

            modelBuilder.Entity("FruitShop.Api.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FruitShop.Api.Models.ProductVariant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UomCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UomFactor")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(1.0000m);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("UomCode");

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("FruitShop.Api.Models.RuleTargetCustomerTier", b =>
                {
                    b.Property<long>("RuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerTier")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("RuleId", "CustomerTier");

                    b.ToTable("RuleTargetCustomerTiers");
                });

            modelBuilder.Entity("FruitShop.Api.Models.RuleTargetVariant", b =>
                {
                    b.Property<long>("RuleId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("VariantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RuleId", "VariantId");

                    b.HasIndex("VariantId");

                    b.ToTable("RuleTargetVariants");
                });

            modelBuilder.Entity("FruitShop.Api.Models.UnitOfMeasure", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasureType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("UnitsOfMeasure", t =>
                        {
                            t.HasCheckConstraint("CK_UnitsOfMeasure_MeasureType", "MeasureType IN ('Weight', 'Count')");
                        });
                });

            modelBuilder.Entity("FruitShop.Api.Models.OrderItem", b =>
                {
                    b.HasOne("FruitShop.Api.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FruitShop.Api.Models.ProductVariant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("FruitShop.Api.Models.PriceRule", b =>
                {
                    b.HasOne("FruitShop.Api.Models.PriceRule", "ParentRule")
                        .WithMany()
                        .HasForeignKey("ParentRuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentRule");
                });

            modelBuilder.Entity("FruitShop.Api.Models.PriceRuleAction", b =>
                {
                    b.HasOne("FruitShop.Api.Models.PriceRule", "Rule")
                        .WithMany("Actions")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("FruitShop.Api.Models.PriceRuleCondition", b =>
                {
                    b.HasOne("FruitShop.Api.Models.PriceRule", "Rule")
                        .WithMany("Conditions")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("FruitShop.Api.Models.ProductVariant", b =>
                {
                    b.HasOne("FruitShop.Api.Models.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FruitShop.Api.Models.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UomCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("FruitShop.Api.Models.RuleTargetCustomerTier", b =>
                {
                    b.HasOne("FruitShop.Api.Models.PriceRule", "Rule")
                        .WithMany("TargetCustomerTiers")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("FruitShop.Api.Models.RuleTargetVariant", b =>
                {
                    b.HasOne("FruitShop.Api.Models.PriceRule", "Rule")
                        .WithMany("TargetVariants")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FruitShop.Api.Models.ProductVariant", "Variant")
                        .WithMany("TargetRules")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("FruitShop.Api.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FruitShop.Api.Models.PriceRule", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Conditions");

                    b.Navigation("TargetCustomerTiers");

                    b.Navigation("TargetVariants");
                });

            modelBuilder.Entity("FruitShop.Api.Models.Product", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("FruitShop.Api.Models.ProductVariant", b =>
                {
                    b.Navigation("TargetRules");
                });
#pragma warning restore 612, 618
        }
    }
}
